name: weather_v2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  card_swiper: ^2.0.4
  date_format: ^2.0.7
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_localization: ^0.1.12
  flutter_riverpod: ^2.3.6
  flutter_translate: ^4.0.4
  geolocator: ^9.0.2
  go_router: ^9.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

